In [4]:
import numpy as dsa

In [5]:
dsa.__version__

'1.26.4'

# Criando Arrays NumPy

In [6]:
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [7]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [8]:
type(arr1)

numpy.ndarray

In [9]:
# Verifando o formatto do array - Neste caso tem uma única dimensão.
arr1.shape

(9,)

In [10]:
arr1[4]

48

In [11]:
arr1[1:4]

array([21, 32, 43])

In [12]:
arr1[1:4+1]

array([21, 32, 43, 48])

In [13]:
# Cria máscara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [14]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [15]:
# Não é permitido incluir elementos de outros tipos
try:
    arr1[0] = 'Novo Elemento'
except:
    print('Não é possível')

Não é possível


# Funções Numpy

In [16]:
arr2 = dsa.array([1, 2, 3, 4, 5])

In [17]:
print(arr2)

[1 2 3 4 5]


In [18]:
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [19]:
# Arange cria um array NumbPy contentdo uma progressão aritmética para partir de um intervalo - start, stop, step
arr3 = dsa.arange(0, 50, 5)

In [20]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [21]:
# Criar um array preenchidos de Zero
arr4 = dsa.zeros(10)

In [22]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
# Retornar 1 nas posições diagonal e 0 no restante
arr5 = dsa.eye(3)

In [24]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# Os Valores passados como arâmetro, formam uma diagonal
arr6 = dsa.diag(dsa.array([1, 2, 3, 4]))

In [26]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [27]:
# Criar uma sequencia numérica igualmente espaçada.
print(dsa.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


# Matrizes com Numpy

In [28]:
# Criando a matriz
arr9 = dsa.array([[1,2,3], [4,5,6]])

print(arr9.shape)

# Manipulação de Arquivos com Numpy

In [29]:
import os
filename = os.path.join('dataset.csv')

In [30]:
# Listar o arquivo
!more dataset.csv

sepal_length,sepal_width,petal_length,petal_width,species
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
4.7,3.2,1.3,0.2,setosa
4.6,3.1,1.5,0.2,setosa
5,3.6,1.4,0.2,setosa
5.4,3.9,1.7,0.4,setosa
4.6,3.4,1.4,0.3,setosa
5,3.4,1.5,0.2,setosa
4.4,2.9,1.4,0.2,setosa
4.9,3.1,1.5,0.1,setosa
5.4,3.7,1.5,0.2,setosa
4.8,3.4,1.6,0.2,setosa
4.8,3,1.4,0.1,setosa
4.3,3,1.1,0.1,setosa
5.8,4,1.2,0.2,setosa
5.7,4.4,1.5,0.4,setosa
5.4,3.9,1.3,0.4,setosa
5.1,3.5,1.4,0.3,setosa
5.7,3.8,1.7,0.3,setosa
5.1,3.8,1.5,0.3,setosa
5.4,3.4,1.7,0.2,setosa
5.1,3.7,1.5,0.4,setosa
4.6,3.6,1,0.2,setosa
5.1,3.3,1.7,0.5,setosa
4.8,3.4,1.9,0.2,setosa
5,3,1.6,0.2,setosa
5,3.4,1.6,0.4,setosa
5.2,3.5,1.5,0.2,setosa
5.2,3.4,1.4,0.2,setosa
4.7,3.2,1.6,0.2,setosa
4.8,3.1,1.6,0.2,setosa
5.4,3.4,1.5,0.4,setosa
5.2,4.1,1.5,0.1,setosa
5.5,4.2,1.4,0.2,setosa
4.9,3.1,1.5,0.1,setosa
5,3.2,1.2,0.2,setosa
5.5,3.5,1.3,0.2,setosa
4.9,3.1,1.5,0.1,setosa
4.4,3,1.3,0.2,setosa
5.1,3.4,1.5,0.2,setosa
5,3.5,1.3,0.3,setosa
4.5,2.3,1.3,0.3,setosa
4.

In [31]:
# Carregando um dataset para dentro de um array
# usecols, pois no array só pode ter um tipo, a ultima coluna é string, não float.
arr13 = dsa.loadtxt(filename, delimiter = ',', usecols = (0,1,2,3), skiprows = 1)

# Análise estatística Básica com NumPy

In [32]:
# Criando o array
arr14 = dsa.array([15, 23, 63, 94, 75])

In [33]:
# Média
dsa.mean(arr14)

54.0

In [34]:
# Desvio padrão (standard Deviation)
dsa.std(arr14)

30.34468652004828

In [35]:
# Variância
dsa.var(arr14)

920.8

# Operações Matemáticas com arrays NumPy

In [36]:
arr15 = dsa.arange(1,10)

In [37]:
print(arr15)

[1 2 3 4 5 6 7 8 9]


In [38]:
# Soma dos elementos do array
dsa.sum(arr15)

45

In [39]:
# Retorna o produto dos elementos
dsa.prod(arr15)

362880

In [40]:
# soma acumulada dos elementos
dsa.cumsum(arr15)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [41]:
# Cria 2 arrays
arr16 = dsa.array([3, 2, 1])
arr17 = dsa.array([1, 2, 3])

In [42]:
# Soma dos arrays
arr18 = dsa.add(arr16, arr17)

In [43]:
print(arr18)

[4 4 4]


In [44]:
# Multiplicação de matrizes
# Criar duas matrizes e conferir se ambas tem mesma quantidade de linhas e colunas
arr19 = dsa.array([[1, 2], [3, 4]])
arr20 = dsa.array([[5, 6], [7, 8]])

In [45]:
arr19.shape

(2, 2)

In [46]:
arr20.shape

(2, 2)

In [47]:
print(arr19)

[[1 2]
 [3 4]]


In [48]:
print(arr20)

[[5 6]
 [7 8]]


In [49]:
# Multiplicar as duas matrizes
arr21 = dsa.dot(arr19, arr20)

In [50]:
print(arr21)

[[19 22]
 [43 50]]


In [52]:
# Outra forma de multiplicar as matrizes
arr21_1 = arr19 @ arr20
print(arr21_1)

[[19 22]
 [43 50]]


# Slicing (fatiamento)

In [54]:
arr22 = dsa.diag(dsa.arange(3))

In [55]:
print(arr22)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [58]:
# buscar indice específico de colune a linha - LINHA , COLUNA
arr22[2,2]

2

In [60]:
# Linha 1
arr22[1]

array([0, 1, 0])

In [62]:
# ignora as linhas e traz os dados da ultima coluna, traz apenas a coluna inteira
arr22[:,2]

array([0, 0, 2])

In [63]:
arr23 = dsa.arange(10)

In [64]:
print(arr23)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
# [start:end:step]
arr23[2:9:3]

array([2, 5, 8])

In [66]:
a = dsa.array([1, 2, 3, 4])
b = dsa.array([1, 2, 3, 4])

In [67]:
# comparação item a item 
a == b

array([ True,  True,  True,  True])

In [69]:
# comparação global
dsa.array_equal(a, b)

True

In [70]:
arr23.min()

0

In [71]:
arr23.max()

9

In [76]:
# somando um valor a cada item do array
arr24 = dsa.array([1, 2, 3]) + 1.5
print(arr24)

[2.5 3.5 4.5]


In [77]:
# arredondamento 
arr25 = dsa.around(arr24)

In [78]:
print(arr25)

[2. 4. 4.]


In [79]:
# Flatten

In [80]:
arr26 = dsa.array([[1,2,3,4], [5,6,7,8]])

In [81]:
print(arr26)

[[1 2 3 4]
 [5 6 7 8]]


In [83]:
# achatando, flatten
arr27 = arr26.flatten()

In [84]:
print(arr27)

[1 2 3 4 5 6 7 8]


In [85]:
# repedindo os elementos de um array
arr28 = dsa.array([1,2,3])

In [87]:
dsa.repeat(arr28, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [88]:
# repetindo os elementos de um array
dsa.tile(arr28, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [89]:
# Criando uma cópia do array
arr30 = dsa.copy(arr28)

In [90]:
print(arr30)

[1 2 3]
